/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package board_proj;

public class TestMain {
    public static void main(String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException {
		String clssName = "board_proj.Sum";
		
		Class<?> cls = Class.forName(clssName);//JVM board_proj.Sum 클래를 로드
		Sum s = (Sum) cls.newInstance();		// board_proj.Sum 를 인스턴스화
		s.add(5, 3);
		
		Sum s2 = new board_proj.Sum();
		s2.add(5,  2);
	}
}
